### ISSUE TITLE
see all repos in user garden on log in 

### ISSUE THREAD

**Issue by shorowitz** [WDI-Bowie-Group-Project/GitGarden#7]

**Comment by jonathanfeudi** [comment]
GH npm module can be used to get all the commits for a repo. Once DB is implemented, should be able to hand repo owner name and repo name into a GH module function in garden.js to retrieve commits for that repo. Tested with dummy data - working.

**Comment by shorowitz** [comment]
we can see all repos in the garden - now to render them appropriately with d3
